
project_id = "nacxysqeciqbtdznnhud"

[functions.analyze-code]
verify_jwt = false

[functions.github-repository]
verify_jwt = true

[functions.detect-yml-config]
verify_jwt = false

[functions.agent-message]
verify_jwt = false

