// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nacxysqeciqbtdznnhud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hY3h5c3FlY2lxYnRkem5uaHVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MTM4MTgsImV4cCI6MjA1NTE4OTgxOH0.z_YdTs367MAqm1ryTlCSfZ6bFRpDLu2nb947E2UwpCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);